### ISSUE TITLE
Support Scala 3

### ISSUE THREAD

**Issue by mlachkar** [scalameta/metaconfig#103]
Since this library contains macro, Scalafix cannot cross-compile in Scala3

**Comment by olafurpg** [comment]
Thank you for reporting! It would be great to add Scala 3 support to Metaconfig but it’s not something I will personally prioritize. I have been working on a metaconfig replacement for over one year now, which lives in the Scalameta/moped repo. 

My thinking about Scala 3 support has been 

- keep metaconfig on Scala 2, use 2.13/3 sandwich where necessary to unblock Scala 3 support in downstream tools (basically only Scalafix and Scalafmt)
- support Scala 3 with Moped at one point and eventually migrate Scalafmt and scalafix to Moped


These are just rough thoughts. Please don’t let these ideas block progress with porting metaconfig to Scala 3 if that’s necessary.
