### ISSUE TITLE
Support Scala 3 Native

### ISSUE THREAD

**Issue by floating-cat** [scalameta/metaconfig#179]
Hi,
From my [checking](https://mvnrepository.com/artifact/com.geirsson/metaconfig-core), this project doesn't support Scala 3 Native.
Can this library add Scala 3 Native support?
Thanks.

**Comment by floating-cat** [comment]
Have a quick check of this project's project build.sbt, it seems the only dependency that doesn't support Scala 3 Native is paiges-core.

**Comment by tgodzik** [comment]
Thanks for reporting! I think we should be able to do that, especially that we can use the 2.13 libraries in case we are lacking the Scala 3 equivalents. Though I think no one was looking into that yet. Would you be interested in taking a look? I can help out if you get stuck at any point.

**Comment by floating-cat** [comment]
@tgodzik Yes, I will check it.

**Comment by tgodzik** [comment]
Thanks!

**Comment by floating-cat** [comment]
I have created an issue to advise the [paiges](https://github.com/typelevel/paiges) library to cut a release that has Scala 3 native support (they have already this Scala 3 native in the main branch). Once they have cut a release, I will try to make a PR for this issue.
